const KEY_UP = "ArrowUp";
const KEY_RIGHT = "ArrowRight";
const KEY_DOWN = "ArrowDown";
const KEY_LEFT = "ArrowLeft";
const KEY_SPACE = " ";
const KEY_CTRL = "Control";

const KEY_Z = "Z";
const KEY_X = "X";
const KEY_C = "C";
const KEY_V = "V";

const FPS = 60;
const EARTH = 70;
const GRAVITY = 0.4;

//COMIENZAN LAS IMAGENES 
    //ITEMS
    const POTION_HALF_HEART = '/img/ITEMS/POTIONS/POTION_HALF_HEART.png'
    const POTION_FULL_HEART = '/img/ITEMS/POTIONS/POTION_FULL_HEART.png'
    const POTION_POWER_UP = '/img/ITEMS/POTIONS/POTION_POWER_UP.png'
    const POTION_FULL_LIFE = '/img/ITEMS/POTIONS/POTION_FULL_LIFE.png'

    //HEARTS
    const HEART = '/img/GOUSTY/Hearts/HEART.png'
    const HALF_HEART ='/img/GOUSTY/Hearts/HALF_HEART.png'
    const NO_HEART = '/img/GOUSTY/Hearts/NO_HEART.png'
    //MP
    const SHADOWPOINTS1 =  '/img/GOUSTY/MP/SHADOWPOINTS1.png'
    const SHADOWPOINTS2 =  '/img/GOUSTY/MP/SHADOWPOINTS2.png'
    const SHADOWPOINTS3 =  '/img/GOUSTY/MP/SHADOWPOINTS3.png'
    const SHADOWPOINTS4 =  '/img/GOUSTY/MP/SHADOWPOINTS4.png'

    //Flechas
    const DOWN_ARROW = '/img/TRANSITION/Map_Arrow_Down.png'
    const RIGTH_ARROW = '/img/TRANSITION/Map_Arrow_Rigth.png'

    //Circulo de transicion
    const CIRCLE = '/img/TRANSITION/Map_Transition.png'

//SWORDS GOUSTY ANIMATIONS
    // SWORDS FRAMES ON AIR
    const SWORD_ON_AIR_DOWN_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_DOWN_LOOKING_LEFT.png'
    const SWORD_ON_AIR_DOWN_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_DOWN_LOOKING_RIGTH.png'
    const SWORD_ON_AIR_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_LEFT.png'
    const SWORD_ON_AIR_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_RIGTH.png'
    const SWORD_ON_AIR_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_UP_LOOKING_LEFT.png'
    const SWORD_ON_AIR_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_UP_LOOKING_RIGTH.png'

    // SWORDS FRAMES ON EARTH
    const SWORD_ON_EARTH_LOOKING_RIGTH1 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_RIGTH1.png'
    const SWORD_ON_EARTH_LOOKING_RIGTH2 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_RIGTH2.png'
    const SWORD_ON_EARTH_LOOKING_LEFT1 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_LEFT1.png'
    const SWORD_ON_EARTH_LOOKING_LEFT2 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_LEFT2.png'
    const SWORD_ON_EARTH_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_UP_LOOKING_LEFT.png'
    const SWORD_ON_EARTH_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_UP_LOOKING_RIGTH.png'

    // GOUSTY USING SWORDS FRAMES ON AIR
    const GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_LEFT.png'
    const GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_RIGTH.png'
    const GOUSTY_SWORD_ON_AIR_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_LEFT.png'
    const GOUSTY_SWORD_ON_AIR_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_RIGTH.png'
    const GOUSTY_SWORD_ON_AIR_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_UP_LOOKING_LEFT.png'
    const GOUSTY_SWORD_ON_AIR_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_UP_LOOKING_RIGTH.png'

    // GOUSTY USING SWORDS FRAMES ON EARTH
    const GOUSTY_SWORD_ON_EARTH_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_LOOKING_LEFT.png'
    const GOUSTY_SWORD_ON_EARTH_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_LOOKING_RIGTH.png'
    const GOUSTY_SWORD_ON_EARTH_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_UP_LOOKING_LEFT.png'
    const GOUSTY_SWORD_ON_EARTH_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_UP_LOOKING_RIGTH.png'
    
    // GOUSTY WALKING
    const GOUSTY_WALKING_LEFT = "/img/GOUSTY/MOVE&STAY/Gousty_Sprite_Left.png"
    const GOUSTY_WALKING_RIGTH = "/img/GOUSTY/MOVE&STAY/Gousty_Sprite.png"

    // GOUSTY LOADING AND SHADOWBALL
    const SHADOWBALL = '/img/GOUSTY/ShadowBall/SHADOWBALL.png'
    const GOUSTY_LOADING_RIGTH = "/img/GOUSTY/ShadowBall/GOUSTY_LOADING_RIGTH.png"
    const GOUSTY_LOADING_LEFT = "/img/GOUSTY/ShadowBall/GOUSTY_LOADING_LEFT.png"

    // GOUSTY JUMPING
    const GOUSTY_JUMPING_RIGTH = '/img/GOUSTY/OnAir/GOUSTY_JUMPING_RIGTH.png'
    const GOUSTY_JUMPING_LEFT = '/img/GOUSTY/OnAir/GOUSTY_JUMPING_LEFT.png'

    // GOUSTY FALLING
    const GOUSTY_FALLING_RIGTH = '/img/GOUSTY/OnAir/GOUSTY_FALLING_RIGTH.png'
    const GOUSTY_FALLING_LEFT = '/img/GOUSTY/OnAir/GOUSTY_FALLING_LEFT.png'

    // GOUSTY CRYING
    const GOUSTY_CRYING_RIGTH = '/img/GOUSTY/NoHitable/GOUSTY_CRYING_RIGTH.png'
    const GOUSTY_CRYING_LEFT = '/img/GOUSTY/NoHitable/GOUSTY_CRYING_LEFT.png'

    //GAME OVER
    const GOUSTY_GAMEOVER = '/img/GOUSTY/Others/GOUSTY_GAMEOVER.png' //no logramos implementarlo
//FIN DE GOUSTY 

    //PLATFORMS
    const PLATFORMS_FOREST_FLOOR = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_FLOOR.png'
    const PLATFORMS_FOREST_PLATFORM_1 = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_PLATFORM_1.png'
    const PLATFORMS_FOREST_PLATFORM_2 = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_PLATFORM_2.png'
    const BACKGROUND_FOREST_WITH_STARS = '/img/BACKGROUND/BACKGROUND/BACKGROUND_FOREST_WITH_STARS.png'

    // INICIO DE MONSTERS
    //FASTSLIME
    const FASTSLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/FastSlime/FASTSLIME_CRYING_LOOKING_LEFT.png'
    const FASTSLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/FastSlime/FASTSLIME_CRYING_LOOKING_RIGTH.png'
    const FASTSLIME_LOOKING_LEFT = '/img/MONSTERS/FastSlime/FASTSLIME_LOOKING_LEFT.png'
    const FASTSLIME_LOOKING_RIGTH = '/img/MONSTERS/FastSlime/FASTSLIME_LOOKING_RIGTH.png'


    //DARKSLIME
    const DARKSLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/DarkSlime/DARKSLIME_CRYING_LOOKING_LEFT.png'
    const DARKSLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/DarkSlime/DARKSLIME_CRYING_LOOKING_RIGTH.png'
    const DARKSLIME_LOOKING_LEFT = '/img/MONSTERS/DarkSlime/DARKSLIME_LOOKING_LEFT.png'
    const DARKSLIME_LOOKING_RIGTH = '/img/MONSTERS/DarkSlime/DARKSLIME_LOOKING_RIGTH.png'

    //DARKSLIME
    const ANGRYSLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/AngrySlime/ANGRYSLIME_CRYING_LOOKING_LEFT.png'
    const ANGRYSLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/AngrySlime/ANGRYSLIME_CRYING_LOOKING_RIGTH.png'
    const ANGRYSLIME_LOOKING_LEFT = '/img/MONSTERS/AngrySlime/ANGRYSLIME_LOOKING_LEFT.png'
    const ANGRYSLIME_LOOKING_RIGTH = '/img/MONSTERS/AngrySlime/ANGRYSLIME_LOOKING_RIGTH.png'

    //FIRESLIME
    const FIRESLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/FireSlime/FIRESLIME_CRYING_LEFT.png'
    const FIRESLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/FireSlime/FIRESLIME_CRYING_RIGTH.png'
    const FIRESLIME_LOOKING_LEFT = '/img/MONSTERS/FireSlime/FIRESLIME_LOOKING_LEFT.png'
    const FIRESLIME_LOOKING_RIGTH = '/img/MONSTERS/FireSlime/FIRESLIME_LOOKING_RIGTH.png'
    const FIRESLIME_ATTACKING_RIGTH = '/img/MONSTERS/FireSlime/FIRESLIME_ATTACKING_RIGTH.png'
    const FIRESLIME_ATTACKING_LEFT = '/img/MONSTERS/FireSlime/FIRESLIME_ATTACKING_LEFT.png'
    const FIRESLIME_FIRE_LEFT = '/img/MONSTERS/FireSlime/FIRE_LEFT.png'
    const FIRESLIME_FIRE_RIGTH = '/img/MONSTERS/FireSlime/FIRE_RIGTH.png'

    //SWORD SLIME
    const SWORDSLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_CRYING_LOOKING_LEFT.png'
    const SWORDSLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_CRYING_LOOKING_RIGTH.png'
    const SWORDSLIME_ATTACKING_LEFT = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_ATTACKING_LEFT.png'
    const SWORDSLIME_ATTACKING_RIGTH = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_ATTACKING_RIGTH.png'
    const SWORDSLIME_LOOKING_LEFT = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_LOOKING_LEFT.png'
    const SWORDSLIME_LOOKING_RIGTH = '/img/MONSTERS/SWORDSLIME/SWORDSLIME_LOOKING_RIGTH.png'

    //SILVER
    const SILVER_SBEAM_LEFT =  "/img/MONSTERS/SilverSlime/BOMMERANG_LEFT.png"
    const SILVER_SBEAM_RIGTH =  "/img/MONSTERS/SilverSlime/SILVERBALL_RIGTH.png"
    const SILVER_ATTACKING_LEFT =  "/img/MONSTERS/SilverSlime/SILVERSLIME_ATTACKING_LEFT.png"
    const SILVER_ATTACKING_RIGTH  =  "/img/MONSTERS/SilverSlime/SILVERSLIME_ATTACKING_RIGTH.png"
    const SILVER_CRYING_LOOKING_RIGTH =  "/img/MONSTERS/SilverSlime/SILVERSLIME_CRYING_LOOKING_RIGTH.png"
    const SILVER_CRYING_LOOKING_LEFT =  "/img/MONSTERS/SilverSlime/SILVERTSLIME_CRYING_LOOKING_LEFT.png"
    const SILVER_LOOKING_LEFT  =  "/img/MONSTERS/SilverSlime/SILVERSLIME_LOOKING_LEFT.png"
    const SILVER_LOOKING_RIGTH =  "/img/MONSTERS/SilverSlime/SILVERSLIME_LOOKING_RIGTH.png"
    //FIN DE MONSTERS


    //COSAS USADAS EN WEB
    //ESTAS SE TIENEN QUE CAMBIAR MANUALMENTE EN EL HTML SOLO ESTAN AQUI COMO NOCIÓN
    const GOUSTY_FOR_WEB = '/img/WEB/GOUSTY_FOR_WEB.gif'
    const GOUSTY_START_GAME = '/img/WEB/GOUSTY_START_GAME.gif'
    const KEYBOARD = '/img/WEB/KEYBOARD.png' 

    //ESTAS SON LAS ANIMACIONES
    const HELP = '/js/animations/help.json'
    const SIMPLEARROW =  '/js/animations/arrorForGousty.json'
    const PLAYANDPAUSE =  '/js/animations/playPause.json'
    const RESTART =  '/js/animations/restart.json'
    const DOWNARROWS =  '/js/animations//downArrows.json'
    const YESBUTTON =  '/js/animations/yesButton.json'
    const NOTBUTTON =  '/js/animations/noButton.json'
    // FIN DE COSAS WEB

    //INICIO DE LOS AUDIOS
    const BACKGROUND_FOREST_MUSIC = '/audio/BACKGROUND_FOREST_MUSIC.mp3'
    const SHADOWBALL_AUDIO = "/audio/SHADOWBALL.mp3"
    const JUMP = "/audio/JUMP.mp3"