const KEY_UP = "ArrowUp";
const KEY_RIGHT = "ArrowRight";
const KEY_DOWN = "ArrowDown";
const KEY_LEFT = "ArrowLeft";
const KEY_SPACE = " ";
const KEY_CTRL = "Control";

const KEY_Z = "Z";
const KEY_X = "X";
const KEY_C = "C";
const KEY_V = "V";


const FPS = 60;
const EARTH = 70;
const GRAVITY = 0.4;


//COMIENZAN LAS IMAGENES 
    //SWORDS GOUSTY ANIMATIONS
    // SWORDS FRAMES ON AIR
const SWORD_ON_AIR_DOWN_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_DOWN_LOOKING_LEFT.png'
const SWORD_ON_AIR_DOWN_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_DOWN_LOOKING_RIGTH.png'
const SWORD_ON_AIR_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_LEFT.png'
const SWORD_ON_AIR_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_RIGTH.png'
const SWORD_ON_AIR_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_UP_LOOKING_LEFT.png'
const SWORD_ON_AIR_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnAir/SWORD_ON_AIR_UP_LOOKING_RIGTH.png'

    // SWORDS FRAMES ON EARTH
const SWORD_ON_EARTH_LOOKING_RIGTH1 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_RIGTH1.png'
const SWORD_ON_EARTH_LOOKING_RIGTH2 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_RIGTH2.png'
const SWORD_ON_EARTH_LOOKING_LEFT1 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_LEFT1.png'
const SWORD_ON_EARTH_LOOKING_LEFT2 = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_LOOKING_LEFT2.png'
const SWORD_ON_EARTH_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_UP_LOOKING_LEFT.png'
const SWORD_ON_EARTH_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/OnEarth/SWORD_ON_EARTH_UP_LOOKING_RIGTH.png'

    // GOUSTY USING SWORDS FRAMES ON AIR
const GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_LEFT.png'
const GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_DOWN_LOOKING_RIGTH.png'
const GOUSTY_SWORD_ON_AIR_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_LEFT.png'
const GOUSTY_SWORD_ON_AIR_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_RIGTH.png'
const GOUSTY_SWORD_ON_AIR_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_UP_LOOKING_LEFT.png'
const GOUSTY_SWORD_ON_AIR_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnAir/GOUSTY_SWORD_ON_AIR_UP_LOOKING_RIGTH.png'

    // GOUSTY USING SWORDS FRAMES ON EARTH
const GOUSTY_SWORD_ON_EARTH_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_LOOKING_LEFT.png'
const GOUSTY_SWORD_ON_EARTH_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_LOOKING_RIGTH.png'
const GOUSTY_SWORD_ON_EARTH_UP_LOOKING_LEFT = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_UP_LOOKING_LEFT.png'
const GOUSTY_SWORD_ON_EARTH_UP_LOOKING_RIGTH = '/img/GOUSTY/SWORD/GoustyOnEarth/GOUSTY_SWORD_ON_EARTH_UP_LOOKING_RIGTH.png'

    //PLATFORMS
const PLATFORMS_FOREST_FLOOR = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_FLOOR.png'
const PLATFORMS_FOREST_PLATFORM_1 = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_PLATFORM_1.png'
const PLATFORMS_FOREST_PLATFORM_2 = '/img/BACKGROUND/PLATFORMS/PLATFORMS_FOREST_PLATFORM_2.png'
const BACKGROUND_FOREST_WITH_STARS = '/img/BACKGROUND/BACKGROUND/BACKGROUND_FOREST_WITH_STARS.png'




    //PLATFORMS
    const FASTSLIME_CRYING_LOOKING_LEFT = '/img/MONSTERS/FastSlime/FASTSLIME_CRYING_LOOKING_LEFT.png'
    const FASTSLIME_CRYING_LOOKING_RIGTH = '/img/MONSTERS/FastSlime/FASTSLIME_CRYING_LOOKING_RIGTH.png'
    const FASTSLIME_LOOKING_LEFT = '/img/MONSTERS/FastSlime/FASTSLIME_LOOKING_LEFT.png'
    const FASTSLIME_LOOKING_RIGTH = '/img/MONSTERS/FastSlime/FASTSLIME_LOOKING_RIGTH.png'